.stylelintrc.json
.vscode/extensions.json
.vscode/settings.json
package-lock.json
package.json
src/components/Header/BannerImage/BannerImage.module.scss
src/components/Header/HamburgerIcon/HamburgerIcon.module.scss
src/components/Header/Header.module.scss
src/components/Header/NavigationButton/NavigationItem.module.scss
src/components/Header/NavigationButtonContainer/NavigationButtonContainer.module.scss
src/components/PreviousFestival/PreviousFestival.module.scss

Closes [ CSSの記述を自動的に並び替えたい #32 ](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/32)
StyleLintを導入し、CSSのプロパティを自動的（保存時とコマンド実行時）に並び替える
- StyleLintインストール
- 設定ファイル（.stylelintrc.json）の作成
- StyleLintのVSCode拡張機能を推奨事項に追加
- 既存のSCSSファイルをフォーマットした
あくまでStyleLintはリンタなので、本来は静的解析のためのツールだそう。
今回やりたいことは並び替えだけなので、余計な設定は全く追加していない。
設定が並び替えだけなのでよっぽどエラーが出て困ることは無いと思うが、あればその時はStyleLintの設定を見直すかも。
また、globalなcssは基本今後追加しないと思うので、並び替えの対象にはしていない（並び替え対象はscssファイルのみ）
CSSのプロパティの順番をいじっても保存時に並び替えられることを確認。
`npm run stylelint`で全てのファイルにstylelintによるフォーマットが走ることを確認（使わないかも）。
追記：VSCodeの拡張機能を推奨事項に追加したので、各々入れてから動作確認してください
`@recommended`で検索すると出てくるはず？
- UIを変更した場合
- Web申請対応の場合

StyleLintを導入

---

src/components/Header/Header.tsx

Closes [ Scroll On時のログの削除 #40 ](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/40)
スクロール時（ヘッダーの切り離しが起きている時）にコンソールにScrollOnのログが残る（ヘッダーアニメーション実装時の消し忘れ）
- `console.log()`の削除
ごめんなさい。
- UIを変更した場合
- Web申請対応の場合

 Scroll On時のログの削除

---

.vscode/settings.json
next.config.mjs
src/components/Content/ContentImage/ContentImage.module.scss
src/components/Content/ContentTitle/ContentTitle.module.scss
src/components/Content/PageWrapper/PageWrapper.module.scss
src/components/Content/SectionBody/SectionBody.module.scss
src/components/Footer/Footer.module.scss
src/components/Header/BannerImage/BannerImage.module.scss
src/components/Header/HamburgerContent/HamburgerContent.module.scss
src/components/Header/HamburgerIcon/HamburgerIcon.module.scss
src/components/Header/Header.module.scss
src/components/Header/NavigationButton/NavigationDropDown.tsx
src/components/Header/NavigationButton/NavigationItem.module.scss
src/components/Header/NavigationButtonContainer/NavigationButtonContainer.module.scss
src/components/PreviousFestival/PreviousFestival.module.scss
src/styles/variables.scss

Closes [ CSSのメディアクエリを変数化する #31 ](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/31)
sassの機能を使うことで、メディアクエリの記述を変数化し統一したい
- phone用mixinを追加
- これまでのメディアクエリを変更
今後メディアクエリを使用する際は
```
@import "variables"
```
を１行目に追加
```
@include phone {
}
```
を使用してメディアクエリをを適用してください。
スマホ画面にしても、画面の表示が変わっていないことを確認
- UIを変更した場合
- Web申請対応の場合

 CSSのメディアクエリを変数化する 

---

package-lock.json
src/app/faq/page.tsx

Closes [faqページを移行](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/51)
FAQページの内容を移行
- 以前のホームページの内容からfaqページの内容を移植
/faq のページにて確認
- UIを変更した場合
- Web申請対応の場合

faqページデータ反映

---

.github/workflows/deploy.yml

related to [Github ActionsでFTP経由でデプロイする](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/87)
ビルドするworkflowを追加
- UIを変更した場合
- Web申請対応の場合

workflow追加

---

.github/workflows/deploy.yml

ノードのバージョンが違ってActionsが落ちたのでバージョンを修正
`> next build
You are using Node.js 16.20.2. For Next.js, Node.js version >= v18.1[7](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/actions/runs/11136378236/job/30948051379#step:5:8).0 is required.`
- UIを変更した場合
- Web申請対応の場合

workflowのnodeバージョンを更新

---

src/components/Header/Header.module.scss
src/components/Header/Header.tsx
src/styles/style.css

Closes [ style.css内のheaderの消し忘れを消す #38 ](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/38)
style.css内のheaderをCSS モジュールへ移行する
- headerのCSSをCSSモジュールへ移行
- ついでにsns系のstylesも削除（sns-floatの移行では全く使っていない）
多分style.cssは誰も使ってなさそうなので、早めに消してしまいたい
headerのCSSがちゃんと当たっているか（変化がないか）確認
- UIを変更した場合
- Web申請対応の場合

global css内のheader削除

---

.eslintrc.json
src/app/project/template/page.tsx
src/components/Content/ContentBox/ContentBox.module.scss
src/components/Content/ContentImage/ContentImage.module.scss
src/components/Content/ContentImage/ContentImage.tsx
src/components/Content/DecoratedImage/DecoratedImage.module.scss
src/components/Content/DecoratedImage/DecoratedImage.tsx
src/components/Project/BrochureImage/BochureImage.module.scss
src/components/Project/BrochureImage/BochureImage.tsx
src/components/Project/ProjectLogo/ProjectLogo.module.scss
src/components/Project/ProjectLogo/ProjectLogo.tsx
src/components/Project/ProjectTag/ProjectTag.module.scss
src/components/Project/ProjectTag/ProjectTag.tsx
src/styles/phone.css
src/styles/style.css

Closes [projectページを移行](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/45)
企画ページで使用するコンポーネントを実装
テーブルは[企画ページのテーブルを作成](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/84)で実装
- 企画のビラを掲載するコンポーネントを`src\components\Project\BrochureImage\BochureImage.tsx`に実装
- 企画ロゴを掲載するコンポーネントを`src\components\Project\ProjectLogo\ProjectLogo.tsx`に実装
- 企画のタグ(1日目, 2日目等)のコンポーネントを`src\components\Project\ProjectTag\ProjectTag.tsx`に実装
`src\components\Project\ProjectTag\ProjectTag.tsx`
`ProjectTag`コンポーネントに開催日(day1, day2)をつけるとタグがつく
day1, day2の両方をつけると`1・2日目`になる
自由にテキストをつけたい場合は`exclusive`をつけて、`exclusiveText`で表示したいテキストを入れる
`/project/template/`のページで確認
- UIを変更した場合
- Web申請対応の場合

projectページを移行

---

src/app/layout.tsx
src/components/Header/HamburgerContent/HamburgerContent.module.scss
src/components/Header/HamburgerContent/HamburgerContent.tsx
src/components/Header/HamburgerIcon/HamburgerIcon.module.scss
src/components/Header/Header.module.scss
src/components/Header/Header.tsx
src/components/Header/NavigationButtonContainer/NavigationButtonContainer.module.scss
src/components/Sns/SnsIcon.tsx
src/components/Sns/SnsIconList.module.scss
src/components/Sns/SnsIconList.tsx

Closes [ sns-floatを移行 #11 ](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/11)
コンポーネントを作成して、src\app\layout.tsxのsns-floatのコメントアウト部分に配置する
- SnsIconの作成
- SnsIconListの作成
- SnsIconListをヘッダーとLayoutに追加
SnsIconListは同じコンポーネントをヘッダーとLayoutに用いている。
Layoutに用いているものは、propとしてpcOnlyを渡すことでスマホ画面では表示しないようにした。
- スマホとPCでSNSアイコンが表示されること
- 押したら新規タブが作成されページが遷移すること
- ホバー中にアイコンにアニメーションが付いていること
- （ヘッダーのCSSを変更したため）ヘッダーのアニメーションが壊れていないこと
- ヘッダー（PC画面）の配置に違和感がないこと
- ハンバーガーアイコンの配置に違和感がないこと
- UIを変更した場合
- Web申請対応の場合

 sns-floatを移行 

---

src/components/PreviousFestival/PreviousFestival.module.scss
src/components/PreviousFestival/PreviousFestival.tsx

Closes [pre-festivalのタイトルを修正 #53](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/53)
「過去のページ」のタイトルをsrc\components\Content\ContentTitle\ContentTitle.tsxコンポーネントに変える
-  preFestivalのタイトルのコンポーネントをContentTitleに変更
「過去のページ」を確認
- UIを変更した場合
- Web申請対応の場合

pre-festivalのタイトルを修正

---

package-lock.json
package.json
src/app/layout.tsx
src/components/Header/BannerImage/BannerImage.module.scss
src/components/Header/Header.module.scss
src/components/Header/Header.tsx
src/components/Header/NavigationButton/NavigationButton.tsx
src/components/Header/NavigationButton/NavigationDropDown.tsx
src/components/Header/NavigationButton/NavigationItem.module.scss
src/components/Header/NavigationButtonContainer/NavigationButtonContainer.module.scss
src/components/Header/NavigationButtonContainer/NavigationButtonContainer.tsx
src/styles/style.css

Closes [ Bootstrapを廃止する #35 ](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/35)
bootstrapを廃止するため、ヘッダーでbootstrapを使用している箇所をリファクタリングする
- bootstrapのクラス名を使っている部分の削除
- bootstrapのアンインストール
- CSSの補修
一部CSSやコードの分かりにくい部分を書き換えているが、メディアクエリの書き換えなどは別issueでやるはずなので、差分が大きくなりすぎないよう不要な部分のリファクタリングは行っていない。
bootstrapをアンインストールしたことによって、全体にも少しだけ影響が出ている様子なので確認してほしい。
- UIを変更した場合
- Web申請対応の場合

Bootstrapを廃止する

---

src/app/page.tsx

Closes [ src\app\page.tsx:6の不要なstyleを削除 #100 ](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/100)
src\app\page.tsx:6の style={{ height: "200vh" }}を削除
- src\app\page.tsx:6の style={{ height: "200vh" }}を削除
topページのheightが小さくなっている
- UIを変更した場合
- Web申請対応の場合

 src\app\page.tsx:6の不要なstyleを削除 

---

src/components/Footer/Footer.tsx

Closes [Footerの回と年を修正](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/91)
Footerの回と年を修正
|before|after|
|-|-|
|![image](https://github.com/user-attachments/assets/5bc2f2a1-29d0-41aa-9d2e-dd9911ac873a)|![image](https://github.com/user-attachments/assets/f1cb1ee5-2de2-455c-9a9f-b8947103dc05)|
- UIを変更した場合
- Web申請対応の場合

Footerの回と年を修正

---

package-lock.json
package.json
src/app/layout.tsx
src/components/PageTop/PageTop.module.scss
src/components/PageTop/PageTop.tsx
src/styles/style.scss

Closes [page-topを移行](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/12)
ページトップボタンを実装
- PCでのみ表示するページトップボタンを追加
- PCでのみ表示される
- スクロールしたら表示される(`http://localhost:3000/faq/`で見るとわかりやすい)
- 押したらスムーズに移動する
- UIを変更した場合
- Web申請対応の場合

page topボタンを追加

---

src/app/layout.tsx

Closes [ headのメタデータに著作権情報を追加 #158 ](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/158)
61stにあったが、Nextへの移行方法がわからなくて放置していたTODOに対応する
- 変更1
- 説明が必要なら記述
- 変更2
- UIを変更した場合
- Web申請対応の場合

 headのメタデータに著作権情報を追加 

---

src/components/PageTop/PageTop.module.scss

Closes [Swiperのスライドが、Page Topボタンより上に来てしまう](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/130)
pageTopにz-indexを指定して他の要素に隠れないように変更
- pageTopに`z-index: 100`を適用
|before|after|
|-|-|
|![image](https://github.com/user-attachments/assets/490dd625-95de-497e-91d2-b83ef38da078)|![image](https://github.com/user-attachments/assets/c4c54fe0-a0d5-4e07-95bb-44ca6ccdc818)|
Swiperとかと被せてみて
- UIを変更した場合
- Web申請対応の場合

pageTopにz-indexを適用して前面に表示

---

src/components/Swiper/Card.tsx
src/components/Swiper/CustomSwiper.module.scss
src/components/Swiper/CustomSwiper.tsx
src/components/Swiper/SwiperButtons/SwiperButtons.module.scss
src/components/Swiper/SwiperCard/SwiperCard.module.scss
src/components/Swiper/SwiperCard/SwiperCard.tsx
src/components/Swiper/SwiperCard/SwiperInfo/SwiperInfo.module.scss
src/components/Swiper/SwiperCard/SwiperInfo/SwiperInfo.tsx
src/components/Swiper/SwiperCard/SwiperInfo/SwiperInfoContent.tsx
src/components/Swiper/SwiperCard/SwiperProjectTag/SwiperProjectTag.module.scss
src/components/Swiper/SwiperCard/SwiperProjectTag/SwiperProjectTag.tsx

Closes [ Swiperのスライドにタグをつける #117 ](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/117)
Closes [ Swiperのスライドで、画像の縦横比を自動で判定してCSSのクラスを指定する #138 ](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/138)
Closes [ Swiperのスライドを企画オブジェクトにつなぐ #125 ](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/125)
Swiperにタグを実装
企画オブジェクトへの連結は別PRにしたい
- タグ実装
- 企画オブジェクトから自動でタグなどの情報を生成できるようにつなぐ
- トップページ、企画ページを見て確認
- タグとかCSS崩れてないかとかちゃんと見て
- UIを変更した場合
- Web申請対応の場合

SwiperのSlideにタグを実装

---

src/app/project/template/page.tsx
src/app/project/template/templateProject.tsx
src/components/Swiper/CustomSwiper.tsx

Closes [customSwiperで参照しているテンプレートデータのパス・変数名を修正](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/166)
[createDateの引数をobjectに変更](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/pull/161)で`src\components\Swiper\CustomSwiper.tsx`を変更してなかったので修正
- UIを変更した場合
- Web申請対応の場合

customSwiperで使用するtemplateProjectのパスと変数名を変更

---

.eslintrc.json

Closes [ 不要なimportを自動削除したい #179 ](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/179)
eslintrcにlintの設定を追加し、不要なimportがファイル保存時に消えるように修正
- eslintrcを編集
不要なimprotが自動で削除されることを確認
- UIを変更した場合
- Web申請対応の場合

不要なimportを自動削除できるようeslintrcを修正

---

src/app/access/page.tsx
src/app/character/page.tsx
src/app/project/template/page.tsx

Closes [Projectコンポーネントのchildrenの位置を変更](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/171)
1階層間違ってたのでProjectコンポーネントのchildrenの位置を修正
- Projectコンポーネントのchildrenの位置を修正
- ContentTitleの不要な閉じタグを削除
- UIを変更した場合
- Web申請対応の場合

Projectコンポーネントのchildrenの位置を修正

---

src/app/about/page.tsx

Closes [委員長会の人数が違う](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/199)
委員長会に関する部分の文章を変更し、今後人数が変わっても良いように人数を記載しないようにした
http://localhost:3000/about/
- UIを変更した場合
- Web申請対応の場合

委員長会に関する表記を修正

---

src/app/project/nitech-challenger/nitechChallenger.tsx

Closes [NITechへの挑戦者の景品を追加](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/231)
- 変更1
- 説明が必要なら記述
- 変更2
- UIを変更した場合
- Web申請対応の場合

NITechへの挑戦者の景品を追加

---

src/utils/date.ts

Closes [ 各月の31日にのみ、createDate関数で月が12月に設定される不具合の修正 #246 ](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/246)
Closes [ Swiperの曜日と時間がおかしい #245 ](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/245)
createDate関数の不具合で、曜日が正しく表示されない
- UIを変更した場合
- Web申請対応の場合

 各月の31日にのみ、createDate関数で月が12月に設定される不具合の修正

---

src/app/allProjectData.tsx

Closes [ 企画一覧スワイパースライドのビラを変更したい #251 ](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/251)
- 変更1
- 説明が必要なら記述
- 変更2
- UIを変更した場合
- Web申請対応の場合

企画一覧スワイパースライドのビラ変更

---

src/components/Header/BannerImage/BannerImage.module.scss

Closes [ヘッダーのハンバーガーメニューがはみ出る](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/220)
src/components/Header/BannerImage/BannerImage.module.scss内bannerLinkに`width: 100%`を追加
- bannerLinkに`width: 100%`を追加
- iphone上でははみ出ないことを確認した
- UIを変更した場合
- Web申請対応の場合

ハンバーガーメニューがはみ出る問題の修正

---

src/utils/date.ts
src/utils/formatter.ts

Closes [Swiperの時間がおかしい](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/259)
formatPeriodを修正
- 標準時の違いで時間がズレていた問題を修正
- UIを変更した場合
- Web申請対応の場合

formatPeriodを修正

---

src/app/project/artful-campus/artfulCampus.tsx
src/app/project/booth/booth.tsx
src/app/project/community-street/communityStreet.tsx
src/app/project/excursion-riddles/excursionRiddles.tsx
src/app/project/haunted-house/hauntedHouse.tsx
src/app/project/kouya/kouya.tsx
src/app/project/laboratory-tour/laboratoryTour.tsx
src/app/project/mogi1/mogi1.tsx
src/app/project/mogiten-pr/mogitenPR.tsx
src/app/project/nitech-challenger/nitechChallenger.tsx
src/app/project/nitech-king/nitechKing.tsx
src/app/project/seiyu/seiyu.tsx
src/app/project/shooting-guesser/shootingGuesser.tsx
src/app/project/template/templateProject.tsx
src/app/project/tyuya/tyuya.tsx
src/app/project/vr-coaster/vrCoaster.tsx
src/app/project/vs-dealer/vsDealer.tsx

Closes [ 企画ページのお問合せ先を消す #208 ](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/208)
- お問合せ先消した
faqにあるinfoのメールアドレスは直書きのままで行きますか？
- UIを変更した場合
- Web申請対応の場合

各企画ページのお問い合わせ先を消去

---

src/const/const.ts

Closes [企画の曜日が1日ずれてる](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/269)
企画の曜日が日・月になっていたので曜日をUTC規準に変更
参考: [formatPeriodを修正](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/pull/260)
テスト環境で確認
- UIを変更した場合
- Web申請対応の場合

曜日をUTC規準に変更

---

src/components/Swiper/SwiperCard/SwiperCard.tsx

Closes [Swiperの画像からloading="lazy"を削除](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/277)
Swiperの画像からloading=lazyを削除
- UIを変更した場合
- Web申請対応の場合

Swiperの画像からloading=lazyを削除

---

src/components/Animation/Animation.tsx
src/components/Animation/BottomIn.tsx
src/components/Animation/CenterIn.tsx
src/components/Animation/LeftIn.tsx
src/components/Animation/RightIn.tsx
src/components/Animation/TopIn.tsx
src/components/Content/ContentBox/ContentBox.tsx
src/components/Content/ContentTitle/ContentTitle.tsx
src/types/types.ts

Closes [Animationを移行](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/28)
アニメーションを移行
参考: [Framer Motionでいい感じのアニメーションをシンプルに実装しました](https://zenn.dev/nakaatsu/articles/07b6b8096165e9#3.-%E8%A1%A8%E7%A4%BA%E9%A0%98%E5%9F%9F%E3%81%AB%E5%85%A5%E3%81%A3%E3%81%9F%E3%82%89%E5%8B%95%E3%81%8B%E3%81%99)
参考: [useInView](https://www.framer.com/motion/use-in-view/###margin)
- center, right, left, up, downの5種類のアニメーションを作成
- contentTitleとBoxにアニメションを適用
- propsでアニメーションを指定出来るようにAnimationコンポーネントを作成
適当なContentBoxに対して`duration={3}`とかをつけてみる
- UIを変更した場合
- Web申請対応の場合

アニメーションを移行

---

src/app/project/zip-fm/zipFM.tsx

Closes [ZIPのスピーカーのビラ削除](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/298)
回と時間が間違っていたので削除
- UIを変更した場合
- Web申請対応の場合

ZIPのスピーカーのビラを削除

---

src/app/project/kouya/kouya.tsx
src/app/project/mogiten-pr/mogitenPR.tsx
src/app/project/nitech-challenger/nitechChallenger.tsx
src/app/project/shooting-guesser/shootingGuesser.tsx
src/app/project/spark/spark.tsx
src/components/Animation/Animation.tsx
src/components/Content/ContentBox/ContentBox.module.scss
src/components/Project/BrochureImage/BrochureImage.tsx
src/components/Project/Project/Project.tsx
src/components/Project/ProjectContent/ProjectContent.tsx
src/components/Project/ProjectLogo/ProjectLogo.tsx
src/components/Project/ProjectTag/ProjectTag.module.scss
src/components/Project/ProjectTag/ProjectTag.tsx

Closes [企画ページのレイアウト変更](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/164)
企画ページのレイアウト変更
- ビラが無い場合は企画詳細のタイトルと企画タグを中央に表示するように変更
- ビラがない企画ページのコンテンツを左右に分割
- ビラ・ロゴ・企画タグにアニメーションを適用
|before|after|
|-|-|
|![image](https://github.com/user-attachments/assets/948b76ca-966a-4202-937f-ff8893ae073d)|![image](https://github.com/user-attachments/assets/df8577bb-cb29-4028-be73-da3c978677b6)|
- UIを変更した場合
- Web申請対応の場合

企画ページのレイアウト変更

---

src/app/about/page.tsx
src/app/access/page.tsx
src/app/page.tsx
src/app/sponsor/page.tsx
src/app/timetable/page.tsx
src/app/whats-new/page.module.scss
src/components/Animation/CenterIn.tsx
src/components/PreviousFestival/PreviousFestival.tsx
src/components/Project/ProjectCard/ProjectCard.tsx
src/components/Project/ProjectTag/ProjectTag.tsx
src/components/Sns/SnsIconList.tsx

Closes [Animationを適用](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/287)
アニメーションを適用
- UIを変更した場合
- Web申請対応の場合

アニメーションが適用されていない箇所を修正

---

README.md

Closes [README更新](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/320)
READMEに開発・デプロイに関する説明を追加
READMEに
- 開発工程
- デプロイ方法
- Actions
に関する詳細を追記
https://github.com/Nitech-Festival-Executive-Committee/koudaisai/tree/text/320-update-readme
↑のREADME表示を確認
- UIを変更した場合
- Web申請対応の場合

READMEに開発・デプロイ・Actionsに関する説明を追加

---

src/app/project/booth/booth.tsx
src/app/timetable/page.tsx

Closes [タイムテーブル画像配置修正](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/325)
- タイムテーブル画像配置修正
- booth展の場所を修正
- 変更1
- 説明が必要なら記述
- 変更2
- UIを変更した場合
- Web申請対応の場合

タイムテーブルの画像の配置を修正

---

src/app/AnnouncementsData.tsx

Closes [3Dマップが使えないことをお知らせに追加](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/327)
3Dマップが利用できないことをお知らせに追加
- 変更1
- 説明が必要なら記述
- 変更2
- UIを変更した場合
- Web申請対応の場合

3Dマップが利用できないことをお知らせに追加
